"""initial models

Revision ID: c1170329d557
Revises: 
Create Date: 2024-08-11 20:52:17.215863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1170329d557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('votes', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_election_results_id'), 'election_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_election_results_id'), table_name='election_results')
    op.drop_table('election_results')
    # ### end Alembic commands ###
